### ISSUE TITLE
Please fix dead links in README.md

### ISSUE THREAD

**Issue by joachimmetz** [airbus-cert/bodyfile#2]
FYI the README.md contains several dead links. Since I did not see a LICENSE file of a contribution friendly FOSS license I did not send a PR but filing an issue instead.

The forensics wiki article has moved to https://forensicswiki.xyz/wiki/index.php?title=Bodyfile and recent additions to the article indicate that the format is far from "trivial" (which I assume is intended to mean straight-forward/non-complex in the context of the readme).

**Comment by nbareil** [comment]
Thanks, a license has been added, the broken link has been fixed and the "trivial" comment has been removed.

**Comment by joachimmetz** [comment]
FYI most links in the README are still broken

* https://github.cert.corp/sgarrelou/regrippy "This site can’t be reached"
* http://www.williballenthin.com/forensics/mft/list_mft/ "404 Not Found"
* https://github.cert.corp/CERT/timeliner "This site can’t be reached"

**Comment by nbareil** [comment]
Ouch, thanks.
